### ISSUE TITLE
Avoid layout shift

### ISSUE THREAD

**Issue by djmtype** [rdela/sveltekit-imagetools#3]
The `img` needs `width` and `height` props, otherwise there could be major layout shifting (CLS).

**Comment by rdela** [comment]
Yes, agree, especially now that #1 landed. I am thinking of bringing in the examples from https://github.com/JonasKruckenberg/imagetools/pull/421 since it was closed without merging. I'll ping you here when that's merged and you can review the new examples if you're up for it.

**Comment by rdela** [comment]
See also https://github.com/rdela/sveltekit-imagetools/issues/2#issuecomment-1444069062
